config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :mentorposts
  resources :posts
  resources :mentors do
    resources :comments, only: [:create]
  end
  
  get 'pages/landing'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#landing"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :mentor
  belongs_to :mentee
end

app/models/mentee.rb
class Mentee < User
    has_many :teaching_relationships
    has_many :mentors, through: :teaching_relationships
    has_many :comments
end

app/models/mentor.rb
class Mentor < User
    has_many :teaching_relationships
    has_many :mentees, through: :teaching_relationships
    has_many :comments
end

app/models/mentorpost.rb
class Mentorpost < ApplicationRecord
    validates :title, presence: true
    def oncreate
   
    end
end

app/models/teaching_relationship.rb
class TeachingRelationship < ApplicationRecord
  belongs_to :mentor
  belongs_to :mentee
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @mentor = Mentor.find(params[:mentor_id])
      @comment = @mentor.comments.create(comment_params)
      redirect_to @mentor, notice: 'Comment added successfully!'
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:content).merge(mentee_id: current_user.id)
    end
  end
  

app/controllers/mentorposts_controller.rb
class MentorpostsController < ApplicationController
  before_action :set_mentorpost, only: %i[ show edit update destroy ]

  # GET /mentorposts or /mentorposts.json
  def index
    @mentorposts = Mentorpost.all
  end

  # GET /mentorposts/1 or /mentorposts/1.json
  def show
  end

  # GET /mentorposts/new
  def new
    @mentorpost = Mentorpost.new
  end

  # GET /mentorposts/1/edit
  def edit
  end

  # POST /mentorposts or /mentorposts.json
  def create
    @mentorpost = Mentorpost.new(mentorpost_params)

    respond_to do |format|
      if @mentorpost.save
        format.html { redirect_to mentorpost_url(@mentorpost), notice: "Mentorpost was successfully created." }
        format.json { render :show, status: :created, location: @mentorpost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mentorpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mentorposts/1 or /mentorposts/1.json
  def update
    respond_to do |format|
      if @mentorpost.update(mentorpost_params)
        format.html { redirect_to mentorpost_url(@mentorpost), notice: "Mentorpost was successfully updated." }
        format.json { render :show, status: :ok, location: @mentorpost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mentorpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentorposts/1 or /mentorposts/1.json
  def destroy
    @mentorpost.destroy

    respond_to do |format|
      format.html { redirect_to mentorposts_url, notice: "Mentorpost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mentorpost
      @mentorpost = Mentorpost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mentorpost_params
      params.require(:mentorpost).permit(:title, :body, :description, :credentials, :experience, :availability, :contact)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/mentorposts_helper.rb
module MentorpostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_alert.html.erb
<% if notice %>
    <p class="notice"><%= notice %></p>
<% elsif alert %>
    <p class="alert"><%= alert %></p>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "rails Blog", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <ul class="navbar-nav">
            <%= render 'user/session_manager'%>
        </ul>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar" %>
      <%= render "layouts/alert"%>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/mentorposts/_form.html.erb
<%= form_with(model: mentorpost) do |form| %>
  <% if mentorpost.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mentorpost.errors.count, "error") %> prohibited this mentorpost from being saved:</h2>

      <ul>
        <% mentorpost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mentorposts/_mentorpost.html.erb
<div id="<%= dom_id mentorpost %>">
    <h1><%= mentorpost.title %></h1>
</div>

app/views/mentorposts/edit.html.erb
<h1>Editing mentorpost</h1>

<%= render "form", mentorpost: @mentorpost %>

<br>

<div>
  <%= link_to "Show this mentorpost", @mentorpost %> |
  <%= link_to "Back to mentorposts", mentorposts_path %>
</div>

app/views/mentorposts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mentorposts</h1>

<div id="mentorposts">
  <% @mentorposts.each do |mentorpost| %>
    <%= render mentorpost %>
    <p>
      <%= link_to "Show this mentorpost", mentorpost %>
    </p>
  <% end %>
</div>

<%= link_to "New mentorpost", new_mentorpost_path %>

app/views/mentorposts/new.html.erb
<h1>New mentorpost</h1>

<%= render "form", mentorpost: @mentorpost %>

<br>

<div>
  <%= link_to "Back to mentorposts", mentorposts_path %>
</div>

app/views/mentorposts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mentorpost %>

<div>
  <%= link_to "Edit this mentorpost", edit_mentorpost_path(@mentorpost) %> |
  <%= link_to "Back to mentorposts", mentorposts_path %>

  <%= button_to "Destroy this mentorpost", @mentorpost, method: :delete %>
</div>

app/views/pages/landing.html.erb
<div class="container">
    <h1>Pages#landing</h1>
    <p>Find me in app/views/pages/landing.html.erb</p>
    <%= link_to "Mentors", mentorposts_path, class: "btn btn-secondary"%>
</div>

app/views/user/_session_manager.html.erb
 <% if current_user%>
    <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User functionality
          </a>
          <ul class="dropdown-menu dropdonw-menu-lg-end" aria-labelledby="navbarDropdown">
            <li><%= link_to "Mentors", mentorposts_path, class: "dropdown-item" %></li>
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            
            <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item"%></li>
          </ul>
        </li>

<%else%>
    <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
    </li>
<%end%>